### ISSUE TITLE
How can I test on my own dataset

### ISSUE THREAD

**Issue by alukade** [Turoad/CLRNet#10]

**Comment by alukade** [comment]
大佬么么

**Comment by MySuperSoul** [comment]
One way is to organize and transform your dataset to CULane format or tusimple format, then you can reuse much of code of our dataset model. Second way is to implement one new dataset_type and corresponding eval metric.

**Comment by alukade** [comment]
> 



> One way is to organize and transform your dataset to CULane format or tusimple format, then you can reuse much of code of our dataset model. Second way is to implement one new dataset_type and corresponding eval metric.

Thank you for your answer! I have some Tusimple format dataset . Except tusimple.py in datasets folder,is there anything else that needs to be modified? QAQ

**Comment by MySuperSoul** [comment]
> 

Maybe in configs、tools/generate_seg_tusimple.py (we will use this tool to generate seg image)、tusimple_metric, you should be careful with like img_h, img_w, num_classes etc.  You can try it first.

**Comment by alukade** [comment]
> Maybe in configs、tools/generate_seg_tusimple.py (we will use this tool to generate seg image)、tusimple_metric, you should be careful with like img_h, img_w, num_classes etc. You can try it first.
> 
> > > 
> > 
> > 
> > > One way is to organize and transform your dataset to CULane format or tusimple format, then you can reuse much of code of our dataset model. Second way is to implement one new dataset_type and corresponding eval metric.
> > 
> > 
> > Thank you for your answer! I have some Tusimple format dataset . Except tusimple.py in datasets folder,is there anything else that needs to be modified? QAQ

thank you very much！！！
