### ISSUE TITLE
why culane's num_classes is 4+1?do i need to modify the parameter when train on custom dataset?

### ISSUE THREAD

**Issue by AnRanbel** [Turoad/CLRNet#102]
Hi, i found num_classes on config file, I'm wonder why it's 4+1, and by the way, do I need to change the value when train on custom dataset? looking forward to your reply.

**Comment by refresh-te** [comment]
@AnRanbel Hi, have you solved the problem, I train CLRNet with custom dataset in CULane format, will get cuda device-side assert error  , it seems that this error will occur when there are more than 4 lane lines GT.How to solve it?Thanks much!
