### ISSUE TITLE
Error in training with Tusimple

### ISSUE THREAD

**Issue by SchweitzerGAO** [Turoad/CLRNet#11]
I am not really sure how this occurred but this really happened. When iterating the tusimple dataset, it failed and raised expections as below(both on this repo and lanedet repo):
![image](https://user-images.githubusercontent.com/64410968/167295904-57ada412-c60b-48ff-ab9e-0eac27ec662b.png)
I also have a question about the description of Tusimple dataset in both this repo and lanedet:
![image](https://user-images.githubusercontent.com/64410968/167296012-732e2adb-1792-4912-ad96-b2bb069f6c9d.png)
but there are just three such labels in Tusimple, I am not sure whether I downloaded Tusimple completely or not.

Many Thanks if you respond to my questions!

**Comment by Turoad** [comment]
Try generate the mask label as README shows:
```
python tools/generate_seg_tusimple.py --root $TUSIMPLEROOT
```

**Comment by MySuperSoul** [comment]
Q1: This is because you do not generate the mask label manually, try generate tusimple mask label as it says.
Q2: Yes you are right, there are 3 such labels, this is a mistake in readme maybe.

**Comment by SchweitzerGAO** [comment]
Many thanks! I should not have forgotten that step ...

**Comment by zhouning1027** [comment]
TuSimple最新下载的格式和示例的格式不一样怎么办呢？。请问如何解决的呢？
![image](https://github.com/user-attachments/assets/6ee2dacc-49f7-47f8-b46d-49232fa0fb78)
