### ISSUE TITLE
What shall I do with my own image before I input this into a trained model?

### ISSUE THREAD

**Issue by SchweitzerGAO** [Turoad/CLRNet#12]
I want to test the model with my own image and I am wondering how to pre-process the image. Thanks

**Comment by Turoad** [comment]
You can refer to [lanedet](https://github.com/Turoad/lanedet) and its `detect.py`.
![image](https://user-images.githubusercontent.com/36562593/167426776-8b7848dd-1869-452b-b9ee-ecef55c0d3c2.png)
