### ISSUE TITLE
Training completed on custom data, detects only the upper part of lanes

### ISSUE THREAD

**Issue by wonsub-yun** [Turoad/CLRNet#128]
Detection result / GT

![20210427_pyeongdong_blackbox_F_20210427_144621_INF_2 avi_000160](https://github.com/Turoad/CLRNet/assets/57588493/7708429d-4447-4630-9a43-86f6bd6555ef)
![20210427_144621_INF_2 avi_000160](https://github.com/Turoad/CLRNet/assets/57588493/dc711b1e-f3e9-40e9-ada0-35772422b9eb)
![20220322_pyeongdong_blackbox_AM_F_20220322_101028_INF_2 avi_000220](https://github.com/Turoad/CLRNet/assets/57588493/9934ce96-43f9-466b-9da4-e55ddb3527c7)
![20220322_101028_INF_2 avi_000220](https://github.com/Turoad/CLRNet/assets/57588493/ff288c25-274a-47da-9152-d3910b58a97a)
![20210427_pyeongdong_blackbox_F_20210427_144621_INF_2 avi_001560](https://github.com/Turoad/CLRNet/assets/57588493/fabdd03c-40a5-4079-9bea-969fde6956ee)
![20210427_144621_INF_2 avi_001560](https://github.com/Turoad/CLRNet/assets/57588493/a24867b3-abef-495b-a625-ca0b79e9ea59)

In configs/clrnet/clr_resnet18_culane.py, I have changed the image size values like this to match with my custom dataset.

ori_img_w = 1920
ori_img_h = 1080
img_w = 800
img_h = 320

Also in clrnet/datasets/culane.py, line 97, I have changed the ys value to match the height of my dataset.

ys = np.arange(270, 1080, 10) / self.cfg.ori_img_h

So I'm assuming two possibilites.
1. While reading annotations, it has only read the upper portion of it.
2. The test & inference outputs the upper portion of the lanes.

It would be nice to know if there are additional variables to be modified.
Thank you.

**Comment by wonsub-yun** [comment]
Solved the issue by resizing the images and labels corresponding to culane dataset.

**Comment by northeastsquare** [comment]
I met the same problem. If use configs/clrnet/clr_dla34_culane.py, change sample_y, ori_img_w, ori_img_h, 根据自己的数据集
