### ISSUE TITLE
no sample[ 'mask_path']

### ISSUE THREAD

**Issue by hyp7266** [Turoad/CLRNet#13]
keyerrot:'mask_path'
the sample does not have the part of ’mask_path'

**Comment by hyp7266** [comment]
and why “ cls_acc.append(sum(cls_acc_stage) / len(cls_acc_stage))
ZeroDivisionError: division by zero  ”

**Comment by Turoad** [comment]
1. Which config do you use?
2. If using small batch size, it might have images with no positive samples. You can add eps like:
```
sum(cls_acc_stage) / (len(cls_acc_stage) + 1e-6)
```

**Comment by hyp7266** [comment]
sorry，i still have a question why once load dataset，later load the dataset all the time but do not load another dataset which path i have change
