### ISSUE TITLE
How long dose the training phase take?

### ISSUE THREAD

**Issue by GilberteBing** [Turoad/CLRNet#133]
Hello! I would like to train the clrnet, but I think I've got a problem.
The GPU I use is the NVIDIA GeForce RTX 3090. 
The configuration is the default clr_resnet18_culane.py.
But the training will take about 12 days. 
Is it normal? How long does the training phase take? And what type of the GPU you used?
Thanks for your time.

**Comment by huzkun** [comment]
Hello, has this issue been resolved? How many days will it take?
