### ISSUE TITLE
Does this mean I have to modify the implementation of some functions in detect.py to test with my own images?

### ISSUE THREAD

**Issue by SchweitzerGAO** [Turoad/CLRNet#14]
The problem I met is shown on the figure
![image](https://user-images.githubusercontent.com/64410968/167663012-80dce400-071a-4f09-8f89-f3d3f071ddc9.png)
Thanks if you could give some advice on this.

**Comment by FangChengRu** [comment]
You can try that,
`data = self.net.module.get_lanes(data)`
change to
`data = self.net.module.heads.get_lanes(data)`

**Comment by SchweitzerGAO** [comment]
It works! Thank you
