### ISSUE TITLE
Can not chang the dataset which is quoted the first time

### ISSUE THREAD

**Issue by hyp7266** [Turoad/CLRNet#15]
I have a question why once load dataset，later load the dataset all the time while do not load another dataset which path i have change

**Comment by hyp7266** [comment]
> 

thank you for your reply.I also want to know why the training last just two epoch and then it is testing

**Comment by MySuperSoul** [comment]
> > 
> 
> thank you for your reply.I also want to know why the training last just two epoch and then it is testing

It depends on the `eval_ep` in config.  For example, if set `eval_ep = 2` in config, then every 2 epoch it will test and eval once.

**Comment by hyp7266** [comment]
> > > 
> > 
> > 
> > 感谢您的回复。我还想知道为什么训练只持续了两个epoch，然后它正在测试
> 
> 这取决于 in 配置。例如，如果在 config 中设置，则每隔 2 个 epoch 将测试和评估一次。`eval_ep``eval_ep = 2`
Sorry again!why test_split   is  " /driver_23_30frame/05151640_0419.MP4/rs00000.jpg
/driver_23_30frame/05151640_0419.MP4/rs00001.jpg
/driver_23_30frame/05151640_0419.MP4/rs00002.jpg
/driver_23_30frame/05151640_0419.MP4/rs00003.jpg
/driver_23_30frame/05151640_0419.MP4/rs00004.jpg",it can success.
while,the idex increase more ,such as  400,  it  fall,, 
 File "/home/sunpy3/Pytorch/CLRNet-main/clrnet/utils/culane_metric.py", line 137, in culane_metric_v2
    interp_anno = np.array([interp(anno_lane, n=5) for anno_lane in anno],
  File "/home/sunpy3/Pytorch/CLRNet-main/clrnet/utils/culane_metric.py", line 137, in <listcomp>
    interp_anno = np.array([interp(anno_lane, n=5) for anno_lane in anno],
  File "/home/sunpy3/Pytorch/CLRNet-main/clrnet/utils/culane_metric.py", line 63, in interp
    tck,u = splprep([x, y], s=0, t=n, k=min(3, len(points) - 1))
  File "/home/sunpy3/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/scipy/interpolate/fitpack.py", line 157, in splprep
    quiet)
  File "/home/sunpy3/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/scipy/interpolate/_fitpack_impl.py", line 280, in splprep
    task, ipar, s, t, nest, wrk, iwrk, per)
ValueError: Invalid inputs.
"""

**Comment by MySuperSoul** [comment]
> > > > 
> > > 
> > > 
> > > 感谢您的回复。我还想知道为什么训练只持续了两个epoch，然后它正在测试
> > 
> > 
> > 这取决于 in 配置。例如，如果在 config 中设置，则每隔 2 个 epoch 将测试和评估一次。`` eval_ep``eval_ep = 2 ``
> > Sorry again!why test_split   is  " /driver_23_30frame/05151640_0419.MP4/rs00000.jpg
> > /driver_23_30frame/05151640_0419.MP4/rs00001.jpg
> > /driver_23_30frame/05151640_0419.MP4/rs00002.jpg
> > /driver_23_30frame/05151640_0419.MP4/rs00003.jpg
> > /driver_23_30frame/05151640_0419.MP4/rs00004.jpg",it can success.
> > while,the idex increase more ,such as  400,  it  fall,,
> > File "/home/sunpy3/Pytorch/CLRNet-main/clrnet/utils/culane_metric.py", line 137, in culane_metric_v2
> > interp_anno = np.array([interp(anno_lane, n=5) for anno_lane in anno],
> > File "/home/sunpy3/Pytorch/CLRNet-main/clrnet/utils/culane_metric.py", line 137, in 
> > interp_anno = np.array([interp(anno_lane, n=5) for anno_lane in anno],
> > File "/home/sunpy3/Pytorch/CLRNet-main/clrnet/utils/culane_metric.py", line 63, in interp
> > tck,u = splprep([x, y], s=0, t=n, k=min(3, len(points) - 1))
> > File "/home/sunpy3/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/scipy/interpolate/fitpack.py", line 157, in splprep
> > quiet)
> > File "/home/sunpy3/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/scipy/interpolate/_fitpack_impl.py", line 280, in splprep
> > task, ipar, s, t, nest, wrk, iwrk, per)
> > ValueError: Invalid inputs.
> > """

Sorry, I don't understand your question, can you explain more clearly?

**Comment by hyp7266** [comment]
> Sorry, I don't understand your question, can you describe it more clearly?

the situation is success:"Generating prediction output...
rs00000.txt
rs00001.txt
rs00002.txt
rs00003.txt
rs00004.txt
2022-05-12 18:57:05,830 - clrnet.utils.culane_metric - INFO - Calculating metric for List: /public/DataSet/Railway/Rail/list/test_split/test0_normal.txt
2022-05-12 18:57:06,684 - clrnet.utils.culane_metric - INFO - iou thr: 0.50, tp: 0, fp: 0, fn: 25,precision: 0, recall: 0, f1: 0
2022-05-12 18:57:06,685 - clrnet.utils.culane_metric - INFO - Calculating metric for List: /public/DataSet/Railway/Rail/list/test.txt"

While the situation is worry:"Generating prediction output...
rs00000.txt
rs00001.txt
rs00002.txt
rs00003.txt
rs00004.txt
rs00006.txt
rs00007.txt
rs00008.txt
rs00009.txt
rs00010.txt
rs00011.txt
rs00012.txt
rs00013.txt
rs00014.txt
rs00015.txt
rs00016.txt
rs00017.txt
2022-05-12 18:55:19,432 - clrnet.utils.culane_metric - INFO - Calculating metric for List: /public/DataSet/Railway/Rail/list/test_split/test0_normal.txt
multiprocessing.pool.RemoteTraceback:"

at the situation of their content in the output is null

**Comment by hyp7266** [comment]
> > 
> 
> 看来你使用自己的数据集？还是 CULane 数据集？输出为 null 表示此图像中未检测到任何行。
But why is it that the output of the first case can calculate the loss, and the output of the second case is stuck where it is clear that they are both empty text files with different numbers

**Comment by hyp7266** [comment]
![1](https://user-images.githubusercontent.com/95162340/168123717-b6653492-f05e-4aae-8539-15cb00d1a34f.png)
这 above situation is successful to continue，while the follow failed
![2](https://user-images.githubusercontent.com/95162340/168123865-2f676938-4bb5-451a-b207-434bdfb4e46b.png)

**Comment by hyp7266** [comment]
> > 
> 
> It seems that you use your own dataset? Or CULane dataset? The output is null means that there are no lines detected in this image.

the two picture show they all contain the predicted data ，while the secon picture‘s process fail to continue after the first eval_ep
