### ISSUE TITLE
关于在自己视频上效果差（有图）

### ISSUE THREAD

**Issue by 18811598673** [Turoad/CLRNet#19]
作者您好，很感谢你们的杰出工作。
我利用lanedet上的detect.py对自己的数据（已进行resize为culane数据集的大小）进行测试（使用的是您已经训练好的模型culane_resnet18），发现效果不是很好。
图1中弯曲的曲线并没有被识别出来。图2中只识别出来中间的两条线（应该要是4条）且在远端时未能模拟到弯曲的部分。
我觉得不应该是这样的效果，之前也做过condlanenet的culane_resnet18的测试，目前来看condlanenet要好于本次的效果，这与paper中的结论有出入。
![0](https://user-images.githubusercontent.com/101979168/168283075-c4a269f4-076d-4129-bd7a-0b48a534fc6d.jpg)
![461](https://user-images.githubusercontent.com/101979168/168283389-705dbab2-96a4-411f-9e3d-6587e0f168cb.jpg)
当然，我觉得应该是我还有什么地方没注意到才出现上述现象，希望您能指出我可能存在的问题。
这里补充我测试视频的来源，下面是哔哩哔哩的一个视频网站，我截取的是前2分钟的视频，将其分为一张张图片同时resize为（1640，590）即culane的数据图片大小，然后使用detect.py（backbone为culane_res18）对图片生成结果。
如果您能够在忙碌的科研生活中抽空测试一下，我将不胜感激。同时，希望能够看到您的测试结果，以及希望您能够指出您在该视频测试过程中可能遇到的跟我一样的问题。若能够得到您的回答，我感激不尽。
https://www.bilibili.com/video/BV1eF411x75u?spm_id_from=333.999.0.0

**Comment by Turoad** [comment]
Firstly, the model is not trained on your own dataset. It is okay that it cannot perform well. For example, CULane has few curve lanes, so the model may not perform well for curve category.

Secondly, some parameters are importance for the model, e.g., [conf_threshold](https://github.com/Turoad/CLRNet/blob/main/configs/clrnet/clr_resnet18_culane.py#L34).  Higher `conf_threshold` will keep higher precision, but the recall will be lower. For your own custom images, it is better to turn down the `conf_theshold` to keep higher recall.  Because these images are not trained for this model, the model will not return high confidence for detected lanes.

Thirdly, I have tried the model trained on CULane to perform test on Tusimple. For the default setting, e.g., `conf_threshold=0.4`, it may only get near 70 acc, but lower the `conf_thredshold`, it can get near 90 acc. Maybe you could  try it for your images, but I can not promise it will perform well.

I don't do a lot of research on generalization problem, it may have some other methods to improve this, but I don't know. You'd better experiment more.

**Comment by 18811598673** [comment]
> Firstly, the model is not trained on your own dataset. It is okay that it cannot perform well. For example, CULane has few curve lanes, so the model may not perform well for curve category.
> 
> Secondly, some parameters are importance for the model, e.g., [conf_threshold](https://github.com/Turoad/CLRNet/blob/main/configs/clrnet/clr_resnet18_culane.py#L34). Higher `conf_threshold` will keep higher precision, but the recall will be lower. For your own custom images, it is better to turn down the `conf_theshold` to keep higher recall. Because these images are not trained for this model, the model will not return high confidence for detected lanes.
> 
> Thirdly, I have tried the model trained on CULane to perform test on Tusimple. For the default setting, e.g., `conf_threshold=0.4`, it may only get near 70 acc, but lower the `conf_thredshold`, it can get near 90 acc. Maybe you could try it for your images, but I can not promise it will perform well.
> 
> I don't do a lot of research on generalization problem, it may have some other methods to improve this, but I don't know. You'd better experiment more.

非常感谢您的帮忙，调整conf_thredshold确实能够使得识别的线增多，不过准确率也会下降（也就是一些不是车道线的东西也会被识别为线），我对该参数的理解是，有点类似目标检测里的IoU？当高于该值时才会被显示出来，是这样子吗？

**Comment by 18811598673** [comment]
> Firstly, the model is not trained on your own dataset. It is okay that it cannot perform well. For example, CULane has few curve lanes, so the model may not perform well for curve category.
> 
> Secondly, some parameters are importance for the model, e.g., [conf_threshold](https://github.com/Turoad/CLRNet/blob/main/configs/clrnet/clr_resnet18_culane.py#L34). Higher `conf_threshold` will keep higher precision, but the recall will be lower. For your own custom images, it is better to turn down the `conf_theshold` to keep higher recall. Because these images are not trained for this model, the model will not return high confidence for detected lanes.
> 
> Thirdly, I have tried the model trained on CULane to perform test on Tusimple. For the default setting, e.g., `conf_threshold=0.4`, it may only get near 70 acc, but lower the `conf_thredshold`, it can get near 90 acc. Maybe you could try it for your images, but I can not promise it will perform well.
> 
> I don't do a lot of research on generalization problem, it may have some other methods to improve this, but I don't know. You'd better experiment more.

感谢您的回答，我对该参数进行了调整，取得了比之前好许多的效果。

**Comment by SchweitzerGAO** [comment]
@18811598673 您好，请问您使用的配置文件和模型都是resnet18+culane嘛？在输入网络之前有没有对图片进行额外的预处理呢，谢谢！

**Comment by 18811598673** [comment]
> @18811598673 您好，请问您使用的配置文件和模型都是resnet18+culane嘛？在输入网络之前有没有对图片进行额外的预处理呢，谢谢！
我只对图片进行resize操作，变成culane数据的（1640，590）分辨率，就没有了。

**Comment by 18811598673** [comment]
> @18811598673 您好，请问您使用的配置文件和模型都是resnet18+culane嘛？在输入网络之前有没有对图片进行额外的预处理呢，谢谢！

我只对图片进行resize操作，变成culane数据的（1640，590），就没有了。

**Comment by SchweitzerGAO** [comment]
OK，我试试，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 中午11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Turoad/CLRNet] 关于在自己视频上效果差（有图） (Issue #19)





  
@18811598673 您好，请问您使用的配置文件和模型都是resnet18+culane嘛？在输入网络之前有没有对图片进行额外的预处理呢，谢谢！
  
我只对图片进行resize操作，变成culane数据的（1640，590），就没有了。

**Comment by onionysy** [comment]
您好，我和您一样运行时利用lanedet上的detect.py对自己的数据（已进行resize为culane数据集的大小）进行测试，不知道您运行时fps有多少，我运行时fps只有5，但看论文上renst18+culane的运行速度能达到100~200，不知道您是否遇到了相似的问题。另外，我的显卡是titanx。

**Comment by Amber-xuedong** [comment]
您好，CLRNet如何测试自己的单张图片呢？望回答，感激不尽

**Comment by Feobi1999** [comment]
> > @18811598673 您好，请问您使用的配置文件和模型都是resnet18+culane嘛？在输入网络之前有没有对图片进行额外的预处理呢，谢谢！
> 
> 我只对图片进行resize操作，变成culane数据的（1640，590），就没有了。

请问这是在输入之前离线对图像进行了尺寸的修改吗

**Comment by 18811598673** [comment]
都行的，看你自己需求。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月5日(星期三) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Turoad/CLRNet] 关于在自己视频上效果差（有图） (Issue #19)





   
@18811598673 您好，请问您使用的配置文件和模型都是resnet18+culane嘛？在输入网络之前有没有对图片进行额外的预处理呢，谢谢！
  
我只对图片进行resize操作，变成culane数据的（1640，590），就没有了。
  
请问这是在输入之前离线对图像进行了尺寸的修改吗
