### ISSUE TITLE
Aboat  compiling Culane evaluation tools 

### ISSUE THREAD

**Issue by sabadijou** [Turoad/CLRNet#21]
I always get the following error when I want to compile the evaluation tools using "make" command
#############################
CXX src/counter.cpp
In file included from include/lane_compare.hpp:4,
                 from include/counter.hpp:4,
                 from src/counter.cpp:8:
include/spline.hpp:6:10: fatal error: opencv2/core.hpp: No such file or directory
    6 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40: build/src/counter.o] Error 1
#################################

**Although the Opencv C++ requirements are reinstalled, the mentioned error has always been raised.**

Is there any solution to this error?

**Comment by MySuperSoul** [comment]
You can try to install opencv lib by `sudo apt install -y libopencv-dev` and compile the eval tools. By the way, our repo reimplements the evaluation tool using python opencv.

**Comment by sabadijou** [comment]
**Thank you for your answer @Turoad.** 

the mentioned command installs the latest version of Opencv (**Opencv4**). Additionally, the command saves Opencv files in "/user/include/opencv4", so the compiling processes encounter the above error. 

To solve the problem, I've copied the content of  "_**/user/include/opencv4**_" directory to "_**/user/include**_" and also I've replaced lines 1 to 16 of "**_lane_compare.hpp_**" with the following lines. 

`#ifndef LANE_COMPARE_HPP
#define LANE_COMPARE_HPP

#include "spline.hpp"
#include <vector>
#include <iostream>
#include <opencv2/core/version.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc.hpp>
using namespace cv;
using namespace std;`
