### ISSUE TITLE
The test result for test7_cross is 0

### ISSUE THREAD

**Issue by Shirley-bht** [Turoad/CLRNet#25]
Thank you very much for your great work! 
However, I found that the test result of test7_cross was always 0 in the process of reproduction. I don't know if it is my configuration or the model itself that is not good for the cross scene.I would appreciate it if you could give me some advice, thanks again.
![image](https://user-images.githubusercontent.com/59900937/169444855-62ca75ff-3f12-421e-845d-cf65e7cb7e22.png)

**Comment by MySuperSoul** [comment]
In CULane test set, the `cross` scenerio doesn't have ground truth lanes, so this is evaluated by the number of `fp`, `fp` is smaller means performing better in `cross` scenerio.

**Comment by Shirley-bht** [comment]
> Oh, I see, thanks for your answer.
