### ISSUE TITLE
ImportError: cannot import name 'nms_impl' from 'clrnet.ops' (/content/drive/MyDrive/model6/clrnet/clrnet/ops/__init__.py)

### ISSUE THREAD

**Issue by surajTade** [Turoad/CLRNet#31]
The nms_impl does not exist in this GitHub
![Screenshot (91)](https://user-images.githubusercontent.com/101720866/170450749-e4657e21-f597-4097-897c-438df23ae8fa.png)
 repo.

**Comment by surajTade** [comment]
I did, But I think something went wrong earlier.
Now it is working fine, Thank you!
Can you also help me with the setting up of dataset directory and the linking part?

**Comment by MySuperSoul** [comment]
> 

Yes, this is depends on `dataset_path` field in config, like this:
https://github.com/Turoad/CLRNet/blob/51e082db12973943bddefd76fd0d431fcb3350ff/configs/clrnet/clr_resnet18_culane.py#L99

So assume your downloaded CULane dataset stored in `/tmp/CULane`, you can setting up in following steps:
`
cd CLRNet && mkdir data && ln -s /tmp/CULane data/CULane
`

**Comment by surajTade** [comment]
Thank you!

**Comment by ai18435136351** [comment]
I run command python setup.py build develop first, but it still shows the 'ImportError: cannot import name 'nms_impl' from 'clrnet.ops'. What should I do to deal with this error

**Comment by mikaelupupup** [comment]
> I run command python setup.py build develop first, but it still shows the 'ImportError: cannot import name 'nms_impl' from 'clrnet.ops'. What should I do to deal with this error我首先运行命令 python setup.py builddevelop，但它仍然显示“ImportError：无法从‘clrnet.ops’导入名称‘nms_impl’”。我应该怎么处理这个错误

Have you solved this problem? I am also getting an error now：
![image](https://github.com/Turoad/CLRNet/assets/157123719/daa3686b-dd5e-495a-b423-8d955c977d90)
