### ISSUE TITLE
Inference code show no results.

### ISSUE THREAD

**Issue by hieunm1821** [Turoad/CLRNet#44]
Hi, I write the inference code by myself, but it does not show any results. Is it because of pre-processing of the image?
Appreciate any help?
```python
import torch
import cv2
from clrnet.engine.runner import Runner
from clrnet.utils.config import Config

cfg = Config.fromfile("configs/clrnet/clr_resnet18_tusimple.py")
cfg.gpus = 1
cfg.load_from = 'tusimple_r18.pth'
cfg.resume_from = ''
cfg.finetune_from = ''
cfg.seed = 1234

def pre_process_image(path):
    img_w = 800
    img_h = 320
    cut_height = 160 
    image = cv2.imread(path)
    image = image[cut_height:, :, :]
    image = cv2.resize(image, (img_w, img_h))
    image = torch.Tensor([image])
    image = image.permute(0, 3, 1, 2)
    return image

runner = Runner(cfg)
runner.net.eval()

image = pre_process_image("data/tusimple/clips/0531/1492626477558988952/8.jpg")
data = image.cuda()
with torch.no_grad():
    output = runner.net(data)
    lanes = runner.net.module.heads.get_lanes(output)
```

lanes returns a empty list.

**Comment by gallegi** [comment]
The same to me. I could not get the lanes after post processing. I check the confidence scores and they are pretty low

**Comment by hieunm1821** [comment]
Problem solved by using the [lanedet/tools/detect.py](https://github.com/Turoad/lanedet/blob/main/tools/detect.py)

Need to change:
- import library
- line 38: data = self.net.module.heads.get_lanes(data)
- config: width, height, cut_height

Thanks to #46

**Comment by gallegi** [comment]
OK, I got it. Thank you
