### ISSUE TITLE
question about Tensorrt.

### ISSUE THREAD

**Issue by ChenzrMax** [Turoad/CLRNet#5]
Excuse me, I have another question about Tensorrt.
Do you export the pytorch model to onnx model and then use tensorrt to speed up? If so, which opset of onnx do you use, and as I know ROIAlign is not supported in tensorrt for now no matter what the version of onnx opset is.

Hope for your answer.

_Originally posted by @ChenzrMax in https://github.com/Turoad/CLRNet/issues/4#issuecomment-1111898766_

**Comment by Turoad** [comment]
We use the custom operators for onnx and tensorrt.

**Comment by farhuaa** [comment]
> Excuse me, I have another question about Tensorrt. Do you export the pytorch model to onnx model and then use tensorrt to speed up? If so, which opset of onnx do you use, and as I know ROIAlign is not supported in tensorrt for now no matter what the version of onnx opset is.
> 
> Hope for your answer.
> 
> _Originally posted by @ChenzrMax in [#4 (comment)](https://github.com/Turoad/CLRNet/issues/4#issuecomment-1111898766)_

Hello, may I ask how you finally solved this problem?

**Comment by ChenzrMax** [comment]
We ultimately did not adopt the clrnet solution, so we did not continue to advance this work. As far as I know, it can be implemented with a custom operator plugin

**Comment by ChenzrMax** [comment]
@farhuaa We ultimately did not adopt the clrnet solution, so we did not continue to advance this work. As far as I know, it can be implemented with a custom operator Plugin.

**Comment by farhuaa** [comment]
> @farhuaa We ultimately did not adopt the clrnet solution, so we did not continue to advance this work. As far as I know, it can be implemented with a custom operator Plugin.

Okay,thank you very much.
