### ISSUE TITLE
The number of detected lane lines is only one (has figure)

### ISSUE THREAD

**Issue by onionysy** [Turoad/CLRNet#50]
Thank you very much for your excellent work.
I used your network to train and test on my own data set, but found that the effect was not very good. In many cases, only one line was detected in a graph, as shown in the figure. We are sure that we have changed max_LANES to be large enough.
![image](https://user-images.githubusercontent.com/55376216/177679331-f485881e-67ac-4aec-9758-bab329edd3bd.png)
![image](https://user-images.githubusercontent.com/55376216/177679342-841a7613-5e5e-44fa-a7fa-276b7d0bcc56.png)
I don't think it should be like this. This is different from the conclusion in the paper. Could you give me some suggestions?

**Comment by lingxuanhao** [comment]
you can try to decrease the setup threshold
