### ISSUE TITLE
关于Cross Layer Refinement

### ISSUE THREAD

**Issue by 18811598673** [Turoad/CLRNet#6]
您好，我想请教一个问题。
![image](https://user-images.githubusercontent.com/101979168/165924055-63f8373a-de96-4522-9e0b-c401320a5b20.png)
我看论文后面“The refinement Rt takes the Pt as input to get the ROI lane features and then performs two FC layers to get the refined parameter Pt.”，好像Rt只把Pt当成输入？那公式里的Lt是什么用的？（额，我整个公式都没看懂）
希望能够获得您的解答，谢谢。

**Comment by MySuperSoul** [comment]
> 您好，我想请教一个问题。 ![image](https://user-images.githubusercontent.com/101979168/165924055-63f8373a-de96-4522-9e0b-c401320a5b20.png) 我看论文后面“The refinement Rt takes the Pt as input to get the ROI lane features and then performs two FC layers to get the refined parameter Pt.”，好像Rt只把Pt当成输入？那公式里的Lt是什么用的？（额，我整个公式都没看懂） 希望能够获得您的解答，谢谢。

非常感谢你对我们的paper感兴趣～
这个公式的意思是这样的，Rt代表的是一次迭代过程，参数为L_{t - 1}和P_{t - 1}，分别表示为当前层的feature map和lane prior的参数，在Rt当中会做lane feature提取、roi-gather聚合等操作（这里都会用到输入的feature map，也就是L_{t - 1}的作用），最后输出一个参数refine的结果，加到输入的P_{t - 1}上，得到下一层的初始输入。这里是对迭代的这个过程做了一个公式抽象

**Comment by WCUSTC** [comment]
能详细说一下P0怎么初始化prior的吗？多谢~

**Comment by MySuperSoul** [comment]
> 能详细说一下P0怎么初始化prior的吗？多谢~

初始化的原则就是尽量均匀，3/4的prior分布在图片的bottom底部位置，各1/8的prior分布在左右两侧。不过同时我们的prior是用nn.embedding的形式表示，是learnable的，在训练的时候也会改变，学习数据集当中的ground truth线的分布情况。具体的初始化方式我们放出代码之后，可以在代码中看到。

**Comment by WCUSTC** [comment]
> 
感谢回答~~

**Comment by 18811598673** [comment]
> 能详细说一下P0怎么初始化prior的吗？多谢~

**Comment by yangrisheng** [comment]
![image](https://user-images.githubusercontent.com/39787375/173790418-180b513d-e9de-4808-83e6-c699e5666615.png)
不好意思，我想问问等式左边的Pt是指图中的哪个呢？

**Comment by yangrisheng** [comment]
还有就是这个refined P0是ROIGather的输出吗？
