### ISSUE TITLE
single-CPU testing with problems

### ISSUE THREAD

**Issue by lmadkm** [Turoad/CLRNet#74]
Hello guys, I have the question with the benchmarks (CULane&TuSimple) testing following the official guidence, where the output = self.net(data) is so small in about 10^*-3~10^*-4 level, and lane[5] is nearly reach to zero, resulting in the output = self.net.heads.get_lanes(output) is the empty one. What I have done is changing the GPU testing to the single-CPU testing in my code and implement the NMS in cpu manner.

**Comment by anitach2003** [comment]
> Hello guys, I have the question with the benchmarks (CULane&TuSimple) testing following the official guidence, where the output = self.net(data) is so small in about 10^_-3~10^_-4 level, and lane[5] is nearly reach to zero, resulting in the output = self.net.heads.get_lanes(output) is the empty one. What I have done is changing the GPU testing to the single-CPU testing in my code and implement the NMS in cpu manner.

Hi can you help me to run this on CPU and help rewrite the NMS function.that would be awesome if you share an email or a contact way so I contact you.

**Comment by lmadkm** [comment]
> > Hello guys, I have the question with the benchmarks (CULane&TuSimple) testing following the official guidence, where the output = self.net(data) is so small in about 10^_-3~10^_-4 level, and lane[5] is nearly reach to zero, resulting in the output = self.net.heads.get_lanes(output) is the empty one. What I have done is changing the GPU testing to the single-CPU testing in my code and implement the NMS in cpu manner.
> 
> Hi can you help me to run this on CPU and help rewrite the NMS function.that would be awesome if you share an email or a contact way so I contact you.

you can refer to this blog which show how to run LaneATT in single CPU with cpu-implemented Lane NMS:
https://blog.csdn.net/gdc6916/article/details/106130423

**Comment by lmadkm** [comment]
> 

OK I finally solve this problem.
The main reason is I have annotated the line 28 in runner.py : 
`self.net = MMDataParallel(self.net, device_ids=range(self.cfg.gpus)).cuda()`
which cause the pretrained model parameters name mismatch with the loaded model parameters name but it did not raise any errors or warnings when I am testing since the line 43 in net_utils.py is:
`net.load_state_dict(pretrained_model['net'], strict=False)`
which the 'strict' args means whether to check it.
And I finally change the line 28 in runner.py as:
`self.net = MMDataParallel(self.net, device_ids=range(self.cfg.gpus))` in my single CPU testing.
