### ISSUE TITLE
运行setup.py报错

### ISSUE THREAD

**Issue by umie0128** [Turoad/CLRNet#78]
![1](https://user-images.githubusercontent.com/49420977/200214817-6a7448f6-aecb-45c3-96ad-b981f763461b.png)

注释get_extensions函数可以运行 但是会缺少 nms_impl

**Comment by wyl-OvO** [comment]
I've also met with this problem, have you solved it?

**Comment by umie0128** [comment]
> I've also met with this problem, have you solved it?

In README.md:
Only test on Ubuntu18.04 and 20.04 with:
- Python >= 3.8 (tested with Python3.8)
- PyTorch >= 1.6 (tested with Pytorch1.6)
- CUDA (tested with cuda10.2)
- Other dependencies described in `requirements.txt`

did you run setup.pyon window?
你是在window环境下面运行setup.py的吗？

**Comment by wyl-OvO** [comment]
不是，在linux服务器上跑的

**Comment by umie0128** [comment]
> 不是，在linux服务器上跑的

我是在window跑所以不行 但是你Linux上为啥报错我就不清楚了

**Comment by wyl-OvO** [comment]
好的，谢谢：）

**Comment by mikeklm** [comment]
I'm sorry, I'm not able to follow. How were you able to solve this problem? I have it as well. Thanks

**Comment by waqarsqureshi** [comment]
I dont know why this is closed. This is still an open issue, not resolved on Linux machine. I am facing the same issue
