### ISSUE TITLE
Inference Model

### ISSUE THREAD

**Issue by waqarsqureshi** [Turoad/CLRNet#90]
How to use the model for detection on a set of images in a folder.

**Comment by waqarsqureshi** [comment]
You can use the detect.py from the tools at [lanedet](https://github.com/Turoad/lanedet)/[tools](https://github.com/Turoad/lanedet/tree/main/tools)/detect.py

you need to do following changes in the file (line 9-13)
`from clrnet.datasets.process import Process
from clrnet.models.registry import build_net
from clrnet.utils.config import Config
from clrnet.utils.visualization import imshow_lanes
from clrnet.utils.net_utils import load_network`

**Comment by zxx1218** [comment]
> 您可以使用[lanedet](https://github.com/Turoad/lanedet)/[tools](https://github.com/Turoad/lanedet/tree/main/tools)/detect.py 工具中的 detect.py
> 
> 您需要对文件进行以下更改（第 9-13 行） `from clrnet.datasets.process import Process from clrnet.models.registry import build_net from clrnet.utils.config import Config from clrnet.utils.visualization import imshow_lanes from clrnet.utils.net_utils import load_network`

After modifying the code according to your method, I encountered an error while running. Do you know why this is happening?

Data=self. net. module. get_lanes (data)
TypeError: get_lanes() takes 1 position argument but 2 were given
